# Generated by Django 2.2.5 on 2019-10-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=200)),
                ('artiste', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('scrape_link', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('site_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'tickets',
            },
        ),
    ]
