# Generated by Django 2.2.5 on 2019-10-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettable',
            name='price',
            field=models.CharField(default=8000, max_length=300),
            preserve_default=False,
        ),
    ]
